version: "3.3"
services:
  snixr:
    build: .
    ports:
      - "433:433"
    volumes:
      - /etc/letsencrypt/live/snixr.cc/fullchain.pem:/app/certs/cert.pem
      - /etc/letsencrypt/live/snixr.cc/privkey.pem:/app/certs/key.pem
  redis:
    image: "redis:alpine"
